version: '3'
services:
  mongodb:
    image: mongo:5.0
    ports:
      - ${DB_PORT:-27017}:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASS}
    volumes:
      - db-data:/data/db

volumes:
  db-data: