vocab_list = {
    "numbers": {
        "zero": ["zero", "zeros"],
        "one": ["one", "ones"],
        "two": ["two", "twos"],
        "three": ["three", "threes"],
        "four": ["four", "fours"],
        "five": ["five", "fives"],
        "six": ["six", "sixes"],
        "seven": ["seven", "sevens"],
        "eight": ["eight", "eights"],
        "nine": ["nine", "nines"],
        "ten": ["ten", "tens"],
        "hundred": ["hundred", "hundreds"],
    },
    "pronouns": {
        "i": ["i"],
        "you": ["you"],
        "he": ["he", "she", "it"],
        "this": ["this"],
        "that": ["that"],
        "we": ["we"],
        "they": ["they"],
    },
    "question": {
        "which": ["which"],
        "who": ["who"],
        "what": ["what"],
        "how many": ["how many", "how much"],
        "how": ["how"],
    },
    "time": {
        "now": ["now"],
        "today": ["today"],
        "tomorrow": ["tomorrow"],
        "yesterday": ["yesterday"],
        "morning": ["morning"],
        "noon": ["noon"],
        "afternoon": ["afternoon"],
        "o'clock": ["o'clock"],
        "minute": ["minute"],
        "year": ["year"],
        "month": ["month"],
        "day": ["day"],
        "week": ["week"],
        "monday": ["monday"],
        "tuesday": ["tuesday"],
        "wednesday": ["wednesday"],
        "thursday": ["thursday"],
        "friday": ["friday"],
        "saturday": ["saturday"],
        "sunday": ["sunday"],
    },
    "nouns": {
        "person": ["person", "people"],
        "name": ["name", "names"],
        "mom": ["mom", "moms"],
        "dad": ["dad", "dads"],
        "son": ["son", "sons"],
        "daughter": ["daughter", "daughters"],
        "friend": ["friend", "friends"],
        "mr": ["mr", "mrs", "sir"],
        "miss": ["miss", "misses"],
        "teacher": ["teacher", "teachers"],
        "student": ["student", "students"],
        "schoolmate": ["schoolmate", "schoolmates"],
        "doctor": ["doctor", "doctors"],
        "thing": ["thing", "things"],
        "money": ["money", "moneys"],
        "water": ["water", "waters"],
        "tea": ["tea", "teas"],
        "dish": ["dish", "dishes"],
        "rice": ["rice", "rices"],
        "cloth": ["cloth", "clothes"],
        "book": ["book", "books"],
        "table": ["table", "tables"],
        "chair": ["chair", "chairs"],
        "fruit": ["fruit", "fruits"],
        "apple": ["apple", "apples"],
        "glass": ["glass", "glasses"],
        "cup": ["cup", "cups"],
        "tv": ["tv", "television", "televisions"],
        "computer": ["computer", "computers"],
        "movie": ["movie", "movies"],
        "plane": ["plane", "planes"],
        "taxi": ["taxi", "taxis", "taxies"],
        "cat": ["cat", "cats"],
        "dog": ["dog", "dogs"],
        "weather": ["weather", "weathers"],
        "character": ["character", "characters"],
        "home": ["home", "homes"],
        "family": ["family", "families"],
        "school": ["school", "schools"],
        "restaurant": ["restaurant", "restaurants"],
        "shop": ["shop", "shops"],
        "hospital": ["hospital", "hospitals"],
        "station": ["station", "stations"],
        "train": ["train", "trains"],
    },
    "adv/adj": {
        "on": ["on"],
        "above": ["above"],
        "last": ["last"],
        "under": ["under"],
        "below": ["below"],
        "next": ["next"],
        "front": ["front"],
        "back": ["back"],
        "inside": ["inside"],
        "not": ["not"],
        "good": ["good"],
        "big": ["big"],
        "small": ["small"],
        "many": ["many"],
        "few": ["few"],
        "hot": ["hot"],
        "cold": ["cold"],
        "pretty": ["pretty"],
        "happy": ["happy"],
        "very": ["very"],
        "too": ["too"],
        "both": ["both"],
    },
    "verb": {
        "do": ["do", "does", "did"],
        "be": ["be", "am", "is", "are", "was", "were"],
        "have": ["have", "has", "had"],
        "live": ["live", "lives", "lived"],
        "stay": ["stay", "stays", "stayed"],
        "come": ["come", "comes", "came"],
        "go": ["go", "goes", "went"],
        "return": ["return", "returns", "returned"],
        "think": ["think", "thinks", "thought"],
        "eat": ["eat", "eats", "ate"],
        "drink": ["drink", "drinks", "drank"],
        "speak": ["speak", "speaks", "spoke"],
        "look": ["look", "looks", "looked"],
        "see": ["see", "sees", "saw"],
        "listen": ["listen", "listens", "listened"],
        "call": ["call", "calls", "called"],
        "buy": ["buy", "buys", "bought"],
        "drive": ["drive", "drives", "drove"],
        "open": ["open", "opens", "opened"],
        "sit": ["sit", "sits", "sat"],
        "read": ["read", "reads"],
        "write": ["write", "writes", "wrote"],
        "know": ["know", "knows", "knew"],
        "learn": ["learn", "learns", "learned"],
        "work": ["work", "works", "worked"],
        "sleep": ["sleep", "sleeps", "slept"],
        "like": ["like", "likes", "liked"],
        "love": ["love", "loves", "loved"],
        "can": ["can", "could"],
        "rain": ["rain", "rains", "rained"],
        "will": ["will"],
    },
    "conjonction": {"and": ["and"], "or": ["or"]},
}
